//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        public int IdProd { get; set; }
        public string NomPro { get; set; }
        public Nullable<int> NbrPro { get; set; }
        public Nullable<int> IdCat { get; set; }
    }
}
