//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENRE
    {
        public int IdGenre { get; set; }
        public string NomGenre { get; set; }
        public string Image { get; set; }
        public string Taille { get; set; }
        public Nullable<double> Prix { get; set; }
        public string Ref { get; set; }
        public string Description { get; set; }
        public string Couleur { get; set; }
        public Nullable<int> NbrGenre { get; set; }
        public string Etat { get; set; }
        public Nullable<int> IdProd { get; set; }
        public Nullable<int> IdPanier { get; set; }
        public string Nouveau { get; set; }
        public Nullable<double> Reduction { get; set; }
        public Nullable<double> Prix1 { get; set; }
        public string Pour { get; set; }
        public string Date { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdCat { get; set; }
        public Nullable<int> IdUser1 { get; set; }
        public Nullable<int> NbrAch { get; set; }
    }
}
