//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PANIER
    {
        public int IdPanier { get; set; }
        public Nullable<int> NbrProPanier { get; set; }
        public string DateAchat { get; set; }
        public Nullable<double> PrixTotal { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<double> Livraison { get; set; }
    }
}
