//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEUR
    {
        public int IdUser { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string DateNaiss { get; set; }
        public string Email { get; set; }
        public string Mdp { get; set; }
        public string Magasin { get; set; }
        public string Contact { get; set; }
        public string Type { get; set; }
        public string Autorisation { get; set; }
        public string Lieu { get; set; }
        public Nullable<int> IdCat { get; set; }
    }
}
